language: java
jdk:
  - openjdk14
addons:
  apt:
    packages:
      - libdb-dev
      - libgmp3-dev
      - libncurses5-dev
before_install:
  - sudo make install-gnucobol
install:
  - make build
script:
  - make test


